name: Update NAP data - Spain

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # This is required for the push step to work

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python -m scripts.naps.spain

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        branch_name="update-nap-spain-$(date +'%Y-%m-%d')"
        git checkout -b $branch_name
    
    - name: Commit changes
      run: |
        git add data/naps/spain/locations.json
        git commit -m "Automated update $(date -u '+%Y-%m-%d')"
    
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin HEAD:main  # Replace 'main' with your default branch if different
    
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --title "Update NAP data - Spain (Automated, $(date -u '+%Y-%m-%d'))" \
                     --body "This is an automated pull request to update NAP data for Spain." \
                     --base main
